networks:
  restorecommerce:
volumes:
  kafka_data:
  redis_data:
  arangodb_data:
  aragodb_apps_data:
  rustfs_data:
  elasticsearch_data:
services:
  ####################
  # Backing Services #
  ####################
  kafka:
    container_name: kafka
    image: apache/kafka:4.3.0
    restart: ${RESTART:-always}
    hostname: kafka
    profiles:
      - "" #all
      - backing
    ports:
      - "9092:9092"
      - "29092:29092"
    deploy:
      resources:
        limits:
          memory: 3072m
    networks:
      - restorecommerce
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: CONTROLLER://:9093,CLIENT://:9092,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/var/lib/kafka/data
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9090:8080
    depends_on:
      - kafka
    networks:
      - restorecommerce
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: Local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backing
  redis:
    container_name: redis
    hostname: redis
    image: redis:8.2.2-alpine3.22
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backing
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 1024m
    volumes:
      - redis_data:/data
    networks:
      - restorecommerce
    healthcheck:
      test: "redis-cli ping"
  arangodb:
    container_name: arangodb
    hostname: arangodb
    image: arangodb/arangodb:3.12.4
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backing
    ports:
      - "8529:8529"
    deploy:
      resources:
        limits:
          memory: 2048m
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - aragodb_apps_data:/var/lib/arangodb3-apps
    networks:
      - restorecommerce
    environment:
      ARANGO_NO_AUTH: 1
    healthcheck:
      test: "wget -O - arangodb:8529/_api/version | grep 3.12.4"
    # command: arangod --database.auto-upgrade=true
  rustfs:
    container_name: rustfs
    hostname: rustfs
    image: rustfs/rustfs:1.0.0-beta.6-glibc
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backing
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - restorecommerce
    environment:
      RUSTFS_ACCESS_KEY: accessKey1
      RUSTFS_SECRET_KEY: verySecretKey1
      ENDPOINT: rustfs
    volumes:
      - arangodb_data:/data:/data
  elasticsearch:
    container_name: restorecommerce_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    restart: ${RESTART:-always}
    hostname: elasticsearch
    profiles:
      - "" #all
      - backing
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 4096m
    networks:
      - restorecommerce
    environment:
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - cluster.name=cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: "if [[ $$(curl -fsSL 'http://localhost:9200/_cat/health?h=status' | sed -r 's/^[[:space:]]+|[[:space:]]+$$//g') != 'red' ]]; then exit 0; else exit 1; fi"
  kibana:
    container_name: restorecommerce_kibana
    image: docker.elastic.co/kibana/kibana:9.4.2
    restart: ${RESTART:-always}
    hostname: kibana
    profiles:
      - "" #all
      - backing
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - restorecommerce
    depends_on:
      - elasticsearch
    healthcheck:
      test: "exit 0"

  ####################
  # Backend Services #
  ####################

  # Identity service
  identity-srv:
    container_name: restorecommerce_identity_srv
    hostname: identity-srv
    image: ghcr.io/restorecommerce/identity-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50051:50051"
    depends_on:
      - arangodb
      - kafka
      # - console
      - elasticsearch
      - redis
    links:
      - arangodb:arangodb
      - kafka:kafka
      # - console:restorecommerce-console
      - elasticsearch:elasticsearch
      - redis:redis
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # Notification service
  notification-srv:
    container_name: restorecommerce_notification_srv
    hostname: notification-srv
    image: ghcr.io/restorecommerce/notification-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50052:50051"
    depends_on:
      - kafka
      - elasticsearch
      - redis
    links:
      - kafka:kafka
      - elasticsearch:elasticsearch
      - redis:redis
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # Object storage service
  ostorage-srv:
    container_name: restorecommerce_ostorage_srv
    hostname: ostorage-srv
    image: ghcr.io/restorecommerce/ostorage-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50066:50051"
    depends_on:
      - rustfs
      - kafka
      - elasticsearch
      - redis
    links:
      - rustfs:rustfs
      - kafka:kafka
      - elasticsearch:elasticsearch
      - redis:redis
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # Object storage service
  ordering-srv:
    container_name: restorecommerce_ordering_srv
    hostname: ordering-srv
    image: ghcr.io/restorecommerce/ordering-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50065:50051"
    depends_on:
      - arangodb
      - kafka
      - elasticsearch
      - redis
    links:
      - arangodb:arangodb
      - kafka:kafka
      - elasticsearch:elasticsearch
      - redis:redis
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # Object storage service
  catalog-srv:
    container_name: restorecommerce_catalog_srv
    hostname: catalog-srv
    image: ghcr.io/restorecommerce/catalog-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50068:50051"
    depends_on:
      - arangodb
      - kafka
      - elasticsearch
      - redis
    links:
      - arangodb:arangodb
      - kafka:kafka
      - elasticsearch:elasticsearch
      - redis:redis
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # Resource service
  resource-srv:
    container_name: restorecommerce_resource_srv
    hostname: master-data-srv
    image: ghcr.io/restorecommerce/resource-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50053:50051"
    depends_on:
      - arangodb
      - kafka
      - elasticsearch
      - redis
    links:
      - kafka:kafka
      - arangodb:arangodb
      - redis:redis
      - elasticsearch:elasticsearch
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # Facade service
  facade-srv:
    container_name: restorecommerce_facade_srv
    hostname: facade-srv
    image: ghcr.io/restorecommerce/facade-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "5000:5000"
    depends_on:
      - identity-srv
      - resource-srv
      - notification-srv
      - rendering-srv
      - redis
      - access-control-srv
      - kafka
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - identity-srv:identity-srv
      - kafka:kafka
      - notification-srv:notification-srv
      - resource-srv:master-data-srv
      - redis:redis
      - rendering-srv:rendering-srv
      - access-control-srv:access-control-srv
      - scheduling-srv:scheduling-srv
      - ostorage-srv:ostorage-srv
      - ordering-srv:ordering-srv
      - catalog-srv:catalog-srv
      - fulfillment-srv:fulfillment-srv
      - invoicing-srv:invoicing-srv
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # Scheduling service
  scheduling-srv:
    container_name: restorecommerce_scheduling_srv
    hostname: scheduling-srv
    image: ghcr.io/restorecommerce/scheduling-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50054:50051"
      - "3000:3000"
    depends_on:
      - redis
      - kafka
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - kafka:kafka
      - redis:redis
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # Rendering service
  rendering-srv:
    container_name: restorecommerce_rendering_srv
    hostname: rendering-srv
    image: ghcr.io/restorecommerce/rendering-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50057:50051"
    depends_on:
      - kafka
      - elasticsearch
      - redis
      # - console
    links:
      - kafka:kafka
      # - console:restorecommerce-console
      - elasticsearch:elasticsearch
      - redis:redis
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # access control service
  access-control-srv:
    container_name: restorecommerce_access_control_srv
    hostname: access-control-srv
    image: ghcr.io/restorecommerce/access-control-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50061:50051"
    depends_on:
      - arangodb
      - kafka
      - elasticsearch
      - redis
    links:
      - arangodb:arangodb
      - kafka:kafka
      - elasticsearch:elasticsearch
      - redis:redis
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  # PDF rendering service
  pdf-rendering-srv:
    container_name: restorecommerce_pdf_render_srv
    hostname: pdf-rendering-srv
    networks:
      - restorecommerce
    image: ghcr.io/restorecommerce/pdf-rendering-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    # links:
    #   - console:restorecommerce-console
    ports:
      - "3001:50051"
    environment:
      ALLOW_HTTP: "true"
      API_TOKENS: "VBYmqRQxvXlmLyQc5jz5ASxVbYUqJMhM"

  # fulfillment service
  fulfillment-srv:
    container_name: restorecommerce_fulfillment_srv
    hostname: fulfillment-srv
    image: ghcr.io/restorecommerce/fulfillment-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50067:50051"
    depends_on:
      - arangodb
      - kafka
      - elasticsearch
      - redis
    links:
      - arangodb:arangodb
      - kafka:kafka
      - elasticsearch:elasticsearch
      - redis:redis
      - ostorage-srv:ostorage
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE
  
  # invoicing-srv
  invoicing-srv:
    container_name: restorecommerce_invoicing_srv
    hostname: invoicing-srv
    image: ghcr.io/restorecommerce/invoicing-srv:latest
    restart: ${RESTART:-always}
    profiles:
      - "" #all
      - backend
    networks:
      - restorecommerce
    ports:
      - "50069:50051"
    depends_on:
      - arangodb
      - kafka
      - elasticsearch
      - redis
    links:
      - arangodb:arangodb
      - kafka:kafka
      - elasticsearch:elasticsearch
      - redis:redis
      - ostorage-srv:ostorage
    environment:
      NODE_ENV: $NODE_ENV
      redis__offsetStoreInterval: 15000
    env_file:
      - '.default.env'
      - $ENV_FILE

  #####################
  # Frondend Services #
  #####################

  ## static content server / web console (currently not implemented for RC)
  # console:
  #   hostname: restorecommerce-console
  #   container_name: restorecommerce_nginx
  #   image: nginx:latest
  #   profiles:
  #    - "" #all
  #    - frontend
  #   ports:
  #     - "80:8080"
  #   environment:
  #     NGINX_PORT: 8080
  #   volumes:
  #     - ./build/console/dist/:/usr/share/nginx/html/dist/
  #     - ./nginx.template:/etc/nginx/conf.d/nginx.template
  #   command:
  #     /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  #   healthcheck:
  #     test: "exit 0"

  # data:
  #  container_name: restorecommerce_data
  #  hostname: data
  #  image: ghcr.io/restorecommerce/data:latest
  #  profiles:
  #    - "" #all
  #    - dataset
  #  networks:
  #    - restorecommerce
  #  links:
  #    - facade-srv:facade-srv
  #  environment:
  #    NODE_ENV: $NODE_ENV
  #  env_file:
  #    - '.default.env'
  #    - $ENV_FILE